---
apiVersion: tekton.dev/v1
kind: Pipeline
metadata:
  name: e2e-ui-integration-tests
spec:
  workspaces:
    - name: myworkspace
  tasks:
    - name: checkout-ui-tests-repo
      workspaces:
        - name: myworkspacename1
          workspace: myworkspace
      taskRef:
        name: git-clone
      params:
        - name: url
          value: https://github.com/trustification/trustify-ui-tests

    - name: printrepo
      runAfter:
        - checkout-ui-tests-repo
      workspaces:
        - name: myworkspacename2
          workspace: myworkspace
      taskSpec:
        workspaces:
          - name: myworkspacename2
        steps:
          - name: aqui
            image: alpine:latest
            script: |
              #!/usr/bin/env sh
              pwd
              ls -l
              ls "$(workspaces.myworkspacename2.path)"
