---
apiVersion: tekton.dev/v1
kind: Pipeline
metadata:
  name: e2e-ui-integration-tests
spec:
  workspaces:
    - name: myworkspace
  tasks:
    - name: checkout-ui-tests-repo
      workspaces:
        - name: myworkspace
          workspace: myworkspace
      taskRef:
        name: git-clone
      params:
        - name: url
          value: https://github.com/trustification/trustify-ui-tests

    - name: printrepo
      runAfter:
        - checkout-ui-tests-repo
      workspaces:
        - name: myworkspace
          workspace: myworkspace
      taskSpec:
        workspaces:
          - name: myworkspace
        steps:
          - name: aqui
            image: alpine:latest
            script: |
              #!/usr/bin/env sh
              pwd
              ls -l
              ls "$(workspaces.myworkspace.path)"
---
apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  generateName: e2e-ui-integration-tests-run
spec:
  pipelineRef:
    name: e2e-ui-integration-tests
  workspaces:
    - name: myworkspace
      volumeClaimTemplate:
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 10Gi
